## Build stage
FROM node:alpine3.21 AS builder
WORKDIR /usr/src/app
COPY dashboard/package*.json ./
RUN npm install --no-audit --no-fund
COPY dashboard ./
RUN npm run build

## Production stage with nginx
FROM nginx:alpine
COPY dashboard/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
COPY --from=builder /usr/src/app/dist ./

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
